# Generated by Django 5.2.1 on 2025-05-15 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('critique', '0003_artwork_likes_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='image_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='artworks/'),
        ),
    ]
