# Generated by Django 5.2.1 on 2025-05-16 01:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('critique', '0006_critique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction_type', models.CharField(choices=[('HELPFUL', 'Helpful'), ('INSPIRING', 'Inspiring'), ('DETAILED', 'Detailed')], help_text='The type of reaction given to the critique', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('critique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='critique.critique')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='critique_reactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Critique Reaction',
                'verbose_name_plural': 'Critique Reactions',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'critique', 'reaction_type'), name='unique_user_critique_reaction')],
            },
        ),
    ]
