# Generated by Django 5.2.1 on 2025-05-16 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('critique', '0008_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='karma',
            field=models.IntegerField(default=0, help_text='Points earned through positive contributions'),
        ),
    ]
