# Generated by Django 5.2.1 on 2025-05-17 03:55

import artcritique.storage_backends
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('critique', '0009_profile_karma'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=artcritique.storage_backends.PublicMediaStorage(), upload_to='artworks/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, storage=artcritique.storage_backends.PublicMediaStorage(), upload_to='profiles/'),
        ),
        migrations.CreateModel(
            name='KarmaEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0)),
                ('action', models.CharField(max_length=50)),
                ('reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='karma_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Karma Event',
                'verbose_name_plural': 'Karma Events',
                'ordering': ['-created_at'],
            },
        ),
    ]
