# Generated by Django 5.2.1 on 2025-05-18 19:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('critique', '0010_alter_artwork_image_alter_profile_profile_picture_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='critique',
            name='flag_reason',
            field=models.TextField(blank=True, help_text='Reason for flagging the critique', null=True),
        ),
        migrations.AddField(
            model_name='critique',
            name='flagged_by',
            field=models.ManyToManyField(blank=True, related_name='flagged_critiques', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='critique',
            name='hidden_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='critique',
            name='hidden_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hidden_critiques', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='critique',
            name='hidden_reason',
            field=models.TextField(blank=True, help_text='Optional reason for hiding the critique', null=True),
        ),
        migrations.AddField(
            model_name='critique',
            name='is_flagged',
            field=models.BooleanField(default=False, help_text='If true, critique has been flagged for moderation'),
        ),
        migrations.AddField(
            model_name='critique',
            name='is_hidden',
            field=models.BooleanField(default=False, help_text='If true, critique is hidden from public view and only visible to the artist and author'),
        ),
        migrations.AddField(
            model_name='critique',
            name='moderation_status',
            field=models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='APPROVED', help_text='Moderation status of this critique', max_length=20),
        ),
        migrations.CreateModel(
            name='CritiqueReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Reply to the critique')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='critique_replies', to=settings.AUTH_USER_MODEL)),
                ('critique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='critique.critique')),
            ],
            options={
                'verbose_name': 'Critique Reply',
                'verbose_name_plural': 'Critique Replies',
                'ordering': ['-created_at'],
            },
        ),
    ]
