# Generated by Django 5.2.1 on 2025-05-24 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('critique', '0011_critique_flag_reason_critique_flagged_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('USER', 'Regular User'), ('MODERATOR', 'Moderator'), ('ADMIN', 'Administrator')], default='USER', help_text='User role determines permissions in the system', max_length=20),
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
