# Generated by Django 5.2.1 on 2025-05-27 21:46

import artcritique.storage_backends
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('critique', '0013_set_default_user_roles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name of the portfolio folder (e.g., 'Landscape Series', 'Abstract Works')", max_length=200)),
                ('description', models.TextField(blank=True, help_text='Optional description of this portfolio folder')),
                ('is_public', models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('unlisted', 'Unlisted')], default='public', help_text='Visibility level of this portfolio folder', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cover_image', models.ImageField(blank=True, help_text='Optional cover image for the portfolio folder', null=True, storage=artcritique.storage_backends.PublicMediaStorage(), upload_to='folder_covers/')),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly version of the folder name', max_length=250)),
                ('owner', models.ForeignKey(help_text='The user who owns this portfolio folder', on_delete=django.db.models.deletion.CASCADE, related_name='folders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Portfolio Folder',
                'verbose_name_plural': 'Portfolio Folders',
                'ordering': ['-updated_at', '-created_at'],
                'unique_together': {('owner', 'slug')},
            },
        ),
        migrations.AddField(
            model_name='artwork',
            name='folder',
            field=models.ForeignKey(blank=True, help_text='Optional portfolio folder this artwork belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artworks', to='critique.folder'),
        ),
    ]
