# Generated by Django 5.2.1 on 2025-06-03 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('critique', '0014_add_folder_portfolio_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Whether this artwork is published and visible to others'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='seeking_critique',
            field=models.BooleanField(default=False, help_text='Whether the artist is actively seeking critique for this piece'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('unlisted', 'Unlisted')], default='public', help_text='Who can see this artwork', max_length=20),
        ),
    ]
