# Generated by Django 5.2.1 on 2025-06-05 21:01

import artcritique.storage_backends
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('critique', '0015_artwork_is_published_artwork_seeking_critique_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtWorkVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, storage=artcritique.storage_backends.PublicMediaStorage(), upload_to='artwork_versions/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('version_notes', models.TextField(blank=True, help_text='Notes about changes in this version')),
                ('medium', models.CharField(blank=True, max_length=100)),
                ('dimensions', models.CharField(blank=True, max_length=100)),
                ('tags', models.CharField(blank=True, max_length=200)),
                ('artwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='critique.artwork')),
            ],
            options={
                'ordering': ['-version_number'],
                'unique_together': {('artwork', 'version_number')},
            },
        ),
    ]
