# Generated by Django 5.2.1 on 2025-06-11 08:12

import artcritique.storage_backends
import critique.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('critique', '0016_artworkversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='display_order',
            field=models.IntegerField(default=0, help_text='Order for displaying folders in portfolio (lower values appear first)'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='image',
            field=models.ImageField(blank=True, help_text='Supported formats: JPEG, PNG, GIF, WebP, SVG, BMP, TIFF (max 20MB)', null=True, storage=artcritique.storage_backends.PublicMediaStorage(), upload_to='artworks/', validators=[critique.validators.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='artworkversion',
            name='image',
            field=models.ImageField(blank=True, help_text='Supported formats: JPEG, PNG, GIF, WebP, SVG, BMP, TIFF (max 20MB)', null=True, storage=artcritique.storage_backends.PublicMediaStorage(), upload_to='artwork_versions/', validators=[critique.validators.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='folder',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Optional cover image for the portfolio folder. Supported formats: JPEG, PNG, GIF, WebP, SVG, BMP, TIFF (max 20MB)', null=True, storage=artcritique.storage_backends.PublicMediaStorage(), upload_to='folder_covers/', validators=[critique.validators.validate_image_file]),
        ),
    ]
