# Generated by Django 5.2.1 on 2025-07-03 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('critique', '0019_achievementbadge_userachievement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
