# Generated by Django 5.2.1 on 2025-07-03 02:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('critique', '0020_alter_artwork_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='current_version',
            field=models.ForeignKey(blank=True, help_text='Points to the current active version of this artwork', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_for', to='critique.artworkversion'),
        ),
    ]
