# Generated by Django 5.2.1 on 2025-08-25 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('critique', '0022_tag_pairsession_quickcrit_quickcrittag'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='critique_areas',
            field=models.JSONField(blank=True, default=list, help_text="Specific areas the artist wants feedback on (e.g., ['technique', 'composition', 'color'])"),
        ),
    ]
